### PR TITLE
More needle string characters taken into account.

### PR DESCRIPTION
**Pull request by hyuzea**

### CODE REVIEW

**Review by jecolon — COMMENTED** [review]
Hi @yus-ham ! This modification is unecessary given that the existing code already does what you want. This PR doesn't pass the tests because it's not taking Grapheme Clusters into account, just code points. Try adding your test case to the origianl code and run `zig build test` to prove it works.

**Comment by hyuzea** [comment]
@jecolon, thank you, I'm new to zig, previously I used command  `zig test src/Zigstr.zig` for the test. 
And using `zig build test` with the additional test cases still fail for the original solution

**Comment by hyuzea** [comment]
@jecolon, sorry my mistake, title was changed. The original `indexOf()` supports more needle chars but it seem there was bug, only one char in needle taken into account. I've updated the fixes.

**Comment by jecolon** [comment]
Great catch @yus-ham ! Thanks for the help.

**Pull request merged**
